name: BunnyDoors
main: net.jonnay.bunnydoors.BunnyDoors
version: 0.5
author: Jonnay
website: https://github.com/jonnay/BunnyDoors/wiki
softdepend: [Vault, Spout]
commands:
    bunnydoor:
        description: use /bunnydoor help for help!
        permission: bunnydoors.use
        usage: /bunnydoor <subcommand>
    bunnykey:
        description: use /bunnykey help for help!
        permission: bunnydoors.keycmd.use
        uage: /bunnykey <subcommand>